listenAddressSingleHTTPFrontend: 0.0.0.0:1337

logLevel: "DEBUG"

checkForUpdates: false

sectionNavigationStyle: "topbar"

actions:
  - title: Docker Logs Beszel
    popupOnStart: execution-dialog-stdout-only
    icon: <iconify-icon icon="vscode-icons:file-type-log" width="2em" height="2em"></iconify-icon>
    shell: docker logs -n 20 beszel

  - title: Check Disk
    popupOnStart: execution-dialog-stdout-only
    icon: <iconify-icon icon="icon-park:disk" width="2em" height="2em"></iconify-icon>
    shell: df -HT

  - title: Start {{ container.Names }}
    icon: '<iconify-icon icon="pepicons-pop:power-circle-filled" width="1.2em" height="1.2em"  style="color: #82ed50"></iconify-icon>'
    shell: docker start {{ container.Names }}
    entity: container
    trigger: Update container entity file

  - title: Stop {{ container.Names }}
    icon: '<iconify-icon icon="pepicons-pop:power-circle-filled" width="1.2em" height="1.2em"  style="color: #ff2020"></iconify-icon>'
    shell: docker stop {{ container.Names }}
    entity: container
    trigger: Update container entity file

  - title: Restart {{ container.Names }}
    icon: <iconify-icon icon="solar:restart-square-bold" width="1.2em" height="1.2em"></iconify-icon>
    shell: docker restart {{ container.Names }}
    entity: container
    trigger: Update container entity file

  - title: Update container entity file
    shell: 'docker ps -a --format json > /etc/OliveTin/entities/containers.json'
    hidden: true
    execOnStartup: true
    execOnCron: '*/5 * * * *'

entities:
  - file: /etc/OliveTin/entities/containers.json
    name: container

dashboards:
  - title: DockerContainers
    contents:
      - title: ' '
        entity: container
        type: fieldset
        contents:
          - type: display
            title: |
              <iconify-icon icon="vscode-icons:file-type-docker2" width="3em" height="3em"></iconify-icon><strong>{{ container.Names }}</strong>{{ container.Image }}
          - title: 'Start {{ container.Names }}'
          - title: 'Stop {{ container.Names }}'
          - title: 'Restart {{ container.Names }}'
          - type: display
            title: |
              <iconify-icon icon="logos:statuspage" width="2.71em" height="2em"></iconify-icon><strong>{{ container.State }}</strong>{{ container.Status }}
