version: "3.8"
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    user: root
    privileged: true
    volumes:
      - ./config.yaml:/config/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "1337:1337"
    restart: unless-stopped

